title = "Pirate Party India"
languageCode = "en-us"
baseurl = "https://piratepartyindia.com/"
theme = "hugo-geo"

[params]
    # Render the rotating globe in the sidebar
    showglobe = true

    # Google Analytics
    analytics = "UA-88710612-1"

    # Social buttons for sidebar
    github = "https://github.com/PiratePartyIndia/ppi-manifesto"
    twitter = "https://twitter.com/piratepartyindia"
    email = "citizen@piratepartyindia.com"

    # Sidebar profile picture
    profilepic = "img/profile.png"

    # Title/subtitle for the sidebar
    title = "Pirate Party India"
    subtitle = "why join the navy when you can be a pirate?"

